version: '3.3'

services:

    
    db:
      image: mysql:5.6
      volumes:
          - db_data:/var/lib/mysql
      restart: always  
      ports: 
          - "3306:3306" 
      environment:
          TZ: "Europe/Bucharest"
          MYSQL_ROOT_PASSWORD: "rootpwd"
          MYSQL_DATABASE: 'testdb'
          MYSQL_USER: 'testuser'
          MYSQL_PASSWORD: 'testpassword'
          


    php-apache:
        build: .
        depends_on:
          - db    
        image: php:7.2.1-apache
        ports:
            - 80:80
        volumes:
            - ./htdocs:/var/www/html
        environment:
            DB_HOST: db:3306
            DB_NAME: 'testdb'
            DB_USER: 'testuser'
            DB_PASSWORD: 'testpassword'
            TZ: Europe/Bucharest

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8181:80
        volumes:
            - ./phpmyadmin:/var/www/html
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_ROOT_PASSWORD: 'testpassword'        

  
volumes:
    db_data: